// Map of popular global and Desi artists to their real Spotify genres.
// Used as a fallback lookup due to Spotify API's February 2026 Developer mode constraints
// that strip genres, popularity, and followers from API responses.

export const artistGenresMap = {
  // Desi Hip Hop (DHH) & Pakistani Hip Hop
  'jokhay': ['desi hip hop', 'pakistani hip hop', 'dhh'],
  'talha anjum': ['desi hip hop', 'pakistani hip hop', 'dhh'],
  'talha yunus': ['desi hip hop', 'pakistani hip hop', 'dhh'],
  'young stunners': ['desi hip hop', 'pakistani hip hop', 'dhh'],
  'taimour baig': ['desi hip hop', 'pakistani hip hop', 'dhh'],
  'jani': ['desi hip hop', 'pakistani hip hop', 'dhh'],
  'divine': ['desi hip hop', 'indian hip hop', 'dhh'],
  'karma': ['desi hip hop', 'indian hip hop', 'dhh'],
  'raftaar': ['desi hip hop', 'indian hip hop', 'dhh'],
  'krsna': ['desi hip hop', 'indian hip hop', 'dhh'],
  'kr$na': ['desi hip hop', 'indian hip hop', 'dhh'],
  'emiway bantai': ['desi hip hop', 'indian hip hop', 'dhh'],
  'seedhe maut': ['desi hip hop', 'indian hip hop', 'dhh'],
  'mc stan': ['desi hip hop', 'indian hip hop', 'dhh'],
  'bella': ['desi hip hop', 'indian hip hop', 'dhh'],
  'umair': ['desi hip hop', 'pakistani hip hop', 'dhh'],
  'hashim ishaq': ['desi hip hop', 'pakistani hip hop', 'dhh'],
  'rap demon': ['desi hip hop', 'pakistani hip hop', 'dhh'],
  'savage': ['desi hip hop', 'pakistani hip hop', 'dhh'],
  'ujjwal': ['desi hip hop', 'indian hip hop'],

  // Bollywood / Desi Pop / Filmi
  'pritam': ['modern bollywood', 'desi pop', 'filmi'],
  'arijit singh': ['modern bollywood', 'desi pop', 'filmi'],
  'mohit chauhan': ['modern bollywood', 'filmi', 'desi pop'],
  'shashwat sachdev': ['modern bollywood', 'filmi', 'indian classical'],
  'badshah': ['desi hip hop', 'desi pop', 'filmi'],
  'atif aslam': ['modern bollywood', 'pakistani pop', 'filmi'],
  'a.r. rahman': ['filmi', 'modern bollywood', 'indian classical'],
  'ar rahman': ['filmi', 'modern bollywood', 'indian classical'],
  'shreya ghoshal': ['filmi', 'modern bollywood', 'indian classical'],
  'kk': ['filmi', 'modern bollywood', 'indian pop'],
  'sonu nigam': ['filmi', 'classic bollywood', 'indian pop'],
  'sunidhi chauhan': ['filmi', 'modern bollywood', 'indian pop'],
  'jubin nautiyal': ['modern bollywood', 'filmi', 'desi pop'],
  'darshan raval': ['desi pop', 'modern bollywood', 'filmi'],
  'nehha kakkar': ['desi pop', 'filmi', 'modern bollywood'],
  'tony kakkar': ['desi pop', 'filmi'],
  'raftaar': ['desi hip hop', 'desi pop'],
  'king': ['desi pop', 'desi hip hop', 'indian pop'],
  'anuv jain': ['indian indie', 'desi pop'],
  'prateek kuhad': ['indian indie', 'desi pop'],
  'the local train': ['indian indie', 'hindi rock'],
  'diljit dosanjh': ['punjabi pop', 'punjabi hip hop', 'desi pop'],
  'ap dhillon': ['punjabi pop', 'punjabi hip hop', 'desi pop'],
  'shubh': ['punjabi pop', 'punjabi hip hop', 'desi pop'],
  'sidhu moose wala': ['punjabi pop', 'punjabi hip hop', 'desi hip hop'],
  'karan aujla': ['punjabi pop', 'punjabi hip hop', 'desi hip hop'],
  'gurinder gill': ['punjabi pop', 'punjabi hip hop'],
  'intense': ['punjabi pop', 'desi hip hop'],

  // Global Hip Hop / Rap
  'j. cole': ['hip hop', 'rap', 'conscious hip hop'],
  'kendrick lamar': ['hip hop', 'rap', 'conscious hip hop', 'west coast rap'],
  'kanye west': ['hip hop', 'rap', 'chicago rap'],
  'drake': ['canadian hip hop', 'canadian pop', 'hip hop', 'rap'],
  'jack harlow': ['hip hop', 'rap', 'pop rap'],
  'travis scott': ['hip hop', 'rap', 'trap'],
  'eminem': ['hip hop', 'rap', 'detroit hip hop'],
  'post malone': ['pop rap', 'pop', 'r&b'],
  'mac miller': ['hip hop', 'rap', 'pittsburgh rap'],
  'tyler, the creator': ['hip hop', 'rap', 'alternative rap'],
  'playboi carti': ['hip hop', 'rap', 'trap'],
  'lil uzi vert': ['hip hop', 'rap', 'trap'],
  'future': ['hip hop', 'rap', 'trap'],
  'metro boomin': ['hip hop', 'rap', 'trap'],
  '21 savage': ['hip hop', 'rap', 'trap'],
  'gunna': ['hip hop', 'rap', 'trap'],
  'lil baby': ['hip hop', 'rap', 'trap'],
  'juice wrld': ['hip hop', 'rap', 'melodic rap'],
  'xxxtentacion': ['hip hop', 'rap', 'emo rap'],
  'pop smoke': ['hip hop', 'rap', 'brooklyn drill'],
  'central cee': ['uk drill', 'uk hip hop'],
  'dave': ['uk hip hop', 'uk rap'],
  'stormzy': ['grime', 'uk hip hop'],
  'kid cudi': ['alternative hip hop', 'rap', 'pop rap'],
  'asap rocky': ['hip hop', 'rap', 'east coast hip hop'],
  'a$ap rocky': ['hip hop', 'rap', 'east coast hip hop'],
  'jid': ['hip hop', 'rap', 'underground hip hop'],
  'denzel curry': ['hip hop', 'rap', 'underground hip hop'],
  'joey bada$$': ['hip hop', 'rap', 'conscious hip hop'],
  'lil nas x': ['pop rap', 'pop'],
  'kid laroi': ['pop rap', 'pop'],
  'the kid laroi': ['pop rap', 'pop'],
  'doja cat': ['pop', 'pop rap', 'r&b'],
  'megan thee stallion': ['hip hop', 'rap', 'pop rap'],
  'cardi b': ['hip hop', 'rap', 'pop rap'],
  'nicki minaj': ['hip hop', 'rap', 'pop rap'],
  'ice spice': ['hip hop', 'rap', 'bronx drill'],
  'glorilla': ['hip hop', 'rap', 'memphis hip hop'],
  'latto': ['hip hop', 'rap', 'pop rap'],
  'coi leray': ['pop rap', 'rap'],
  'yeat': ['rage rap', 'trap'],
  'ken carson': ['rage rap', 'trap'],
  'destroy lonely': ['rage rap', 'trap'],
  'trippie redd': ['rap', 'trap', 'melodic rap'],
  'lil yachty': ['rap', 'alternative hip hop'],
  'lil tjay': ['rap', 'melodic rap'],
  'polo g': ['rap', 'melodic rap'],
  'lil durk': ['rap', 'drill'],
  'chief keef': ['drill', 'hip hop'],
  'nle choppa': ['rap', 'memphis hip hop'],
  'moneybagg yo': ['rap', 'memphis hip hop'],
  'kodak black': ['rap', 'trap'],
  'young thug': ['hip hop', 'rap', 'trap'],
  'outkast': ['hip hop', 'atlanta hip hop'],
  'ludacris': ['hip hop', 'rap'],
  't.i.': ['hip hop', 'rap', 'trap'],
  'lil wayne': ['hip hop', 'rap'],
  'jay-z': ['hip hop', 'rap'],
  'nas': ['hip hop', 'rap', 'conscious hip hop'],
  'tupac': ['hip hop', 'rap', 'west coast rap'],
  '2pac': ['hip hop', 'rap', 'west coast rap'],
  'notorious b.i.g.': ['hip hop', 'rap', 'east coast hip hop'],
  'dr. dre': ['hip hop', 'rap', 'g-funk'],
  'snoop dogg': ['hip hop', 'rap', 'g-funk'],
  '50 cent': ['hip hop', 'rap'],

  // Global Pop / R&B
  'taylor swift': ['pop', 'synth-pop'],
  'the weeknd': ['pop', 'r&b', 'canadian pop'],
  'billie eilish': ['pop', 'art pop', 'alternative pop'],
  'justin bieber': ['pop', 'canadian pop'],
  'bruno mars': ['pop', 'funk', 'r&b'],
  'ed sheeran': ['pop', 'singer-songwriter'],
  'dua lipa': ['pop', 'dance pop'],
  'ariana grande': ['pop', 'dance pop', 'r&b'],
  'olivia rodrigo': ['pop', 'pop rock'],
  'sza': ['r&b', 'pop', 'neo soul'],
  'frank ocean': ['r&b', 'neo soul', 'alternative r&b'],
  'joji': ['alternative r&b', 'indie pop'],
  'lana del rey': ['art pop', 'indie pop', 'alternative pop'],
  'harry styles': ['pop', 'indie pop'],
  'shawn mendes': ['pop', 'canadian pop'],
  'khalid': ['pop', 'r&b'],
  'lauv': ['pop', 'indie pop'],
  'adele': ['pop', 'soul'],
  'sam smith': ['pop', 'soul'],
  'john legend': ['soul', 'r&b', 'pop'],
  'alicia keys': ['r&b', 'soul', 'pop'],
  'beyonce': ['pop', 'r&b'],
  'rihanna': ['pop', 'r&b'],
  'shakira': ['latin pop', 'pop'],
  'lady gaga': ['pop', 'dance pop'],
  'katy perry': ['pop', 'dance pop'],
  'miley cyrus': ['pop', 'pop rock'],
  'selena gomez': ['pop', 'dance pop'],
  'demi lovato': ['pop', 'pop rock'],
  'usher': ['r&b', 'pop'],
  'chris brown': ['r&b', 'pop'],
  'ne-yo': ['r&b', 'pop'],
  'akon': ['pop', 'r&b'],
  't-pain': ['r&b', 'pop rap'],
  'jason derulo': ['pop', 'dance pop'],
  'pitbull': ['pop', 'latin hip hop'],
  'flo rida': ['pop rap', 'dance pop'],
  'charlie puth': ['pop', 'dance pop'],
  'halsey': ['pop', 'alternative pop'],
  'camila cabello': ['pop', 'dance pop'],
  'shawn mendes': ['pop'],
  'zayn': ['pop', 'r&b'],
  'niall horan': ['pop', 'pop rock'],
  'louis tomlinson': ['pop', 'pop rock'],
  'liam payne': ['pop', 'r&b'],

  // Indie / Folk / Alternative
  'hozier': ['indie pop', 'soul', 'alternative rock'],
  'bon iver': ['indie folk', 'alternative rock'],
  'phoebe bridgers': ['indie pop', 'indie folk'],
  'boygenius': ['indie pop', 'indie rock'],
  'clairo': ['indie pop', 'bedroom pop'],
  'rex orange county': ['indie pop', 'bedroom pop'],
  'mitski': ['indie pop', 'art pop', 'alternative rock'],
  'wallows': ['indie pop', 'indie rock'],
  'vance joy': ['indie folk', 'pop'],
  'the neighbourhood': ['indie pop', 'modern rock'],
  'arctic monkeys': ['garage rock', 'indie rock'],
  'coldplay': ['pop rock', 'alternative rock', 'permanent wave'],
  'imagine dragons': ['modern rock', 'pop rock'],
  'twenty one pilots': ['pop rap', 'indie pop'],
  'gorillaz': ['alternative rock', 'indie pop'],
  'conan gray': ['pop', 'bedroom pop', 'indie pop'],
  'girl in red': ['indie pop', 'bedroom pop'],
  'dayglow': ['indie pop', 'bedroom pop'],
  'cuco': ['bedroom pop', 'chicano indie'],
  'steve lacy': ['alternative r&b', 'indie pop'],
  'omar apollo': ['alternative r&b', 'indie pop'],
  'lumineers': ['indie folk', 'stomp and holler'],
  'the lumineers': ['indie folk', 'stomp and holler'],
  'mumford & sons': ['indie folk', 'modern folk'],
  'fleet foxes': ['indie folk', 'chamber pop'],
  'sufjan stevens': ['indie folk', 'chamber pop'],
  'iron & wine': ['indie folk', 'singer-songwriter'],

  // Rock / Metal
  'queen': ['classic rock', 'glam rock', 'rock'],
  'the beatles': ['classic rock', 'psychedelic rock'],
  'pink floyd': ['classic rock', 'progressive rock'],
  'led zeppelin': ['classic rock', 'hard rock'],
  'ac/dc': ['classic rock', 'hard rock'],
  'nirvana': ['grunge', 'alternative rock'],
  'linkin park': ['alternative metal', 'nu metal', 'post-grunge'],
  'green day': ['punk', 'pop punk'],
  'blink-182': ['pop punk', 'punk'],
  'my chemical romance': ['emo', 'pop punk'],
  'paramore': ['pop punk', 'alternative rock'],
  'fall out boy': ['pop punk', 'emo'],
  'panic! at the disco': ['pop', 'pop punk'],
  'foo fighters': ['alternative rock', 'modern rock', 'post-grunge'],
  'red hot chili peppers': ['funk rock', 'alternative rock'],
  'metallica': ['thrash metal', 'metal', 'hard rock'],
  'slipknot': ['alternative metal', 'nu metal', 'metal'],
  'system of a down': ['alternative metal', 'nu metal', 'rock'],
  'avenged sevenfold': ['alternative metal', 'metal'],
  'bring me the horizon': ['modern rock', 'alternative metal', 'metalcore'],

  // Electronic / Dance / House
  'daft punk': ['electronic', 'filter house', 'synth-pop'],
  'calvin harris': ['electronic', 'dance pop', 'edm'],
  'avicii': ['electronic', 'edm'],
  'marshmello': ['electronic', 'edm'],
  'the chainsmokers': ['electronic', 'dance pop', 'edm'],
  'kygo': ['electronic', 'tropical house', 'edm'],
  'martin garrix': ['electronic', 'edm', 'progressive house'],
  'david guetta': ['electronic', 'dance pop', 'edm'],
  'tiesto': ['electronic', 'edm', 'trance'],
  'skrillex': ['electronic', 'edm', 'dubstep'],
  'flume': ['electronic', 'future bass'],
  'odesza': ['electronic', 'indietronica'],
  'rufus du sol': ['electronic', 'indie house'],
  'rūfüs du sol': ['electronic', 'indie house'],
  'disclosure': ['electronic', 'house', 'uk garage'],
  'fred again..': ['electronic', 'house', 'uk dance'],
  'peggy gou': ['electronic', 'house'],
  'four tet': ['electronic', 'ambient'],
  'bonobo': ['electronic', 'downtempo'],
  'tycho': ['electronic', 'chillwave'],
  'tiësto': ['electronic', 'edm'],
  'swedish house mafia': ['electronic', 'edm', 'progressive house'],
  'alesso': ['electronic', 'edm', 'progressive house'],
  'zedd': ['electronic', 'edm', 'dance pop'],
  'deadmau5': ['electronic', 'electro house', 'progressive house'],
  'disclosure': ['electronic', 'house'],
  'kaytranada': ['electronic', 'house', 'hip hop'],

  // Traditional Pop / Jazz / Blues / Soul
  'frank sinatra': ['traditional pop', 'swing', 'easy listening'],
  'michael buble': ['traditional pop', 'swing', 'jazz'],
  'norah jones': ['jazz', 'vocal jazz', 'pop'],
  'miles davis': ['jazz', 'cool jazz'],
  'john coltrane': ['jazz', 'hard bop'],
  'bill evans': ['jazz', 'cool jazz'],
  'louis armstrong': ['jazz', 'traditional jazz'],
  'ella fitzgerald': ['jazz', 'vocal jazz', 'swing'],
  'leon bridges': ['soul', 'r&b', 'retro soul'],
  'alabama shakes': ['soul', 'indie rock'],
  'gary clark jr.': ['blues', 'blues rock', 'soul'],
  'john mayer': ['pop rock', 'singer-songwriter', 'blues rock'],
  'jason mraz': ['pop', 'acoustic pop'],
  'jack johnson': ['acoustic pop', 'singer-songwriter'],

  // Classical / Soundtrack
  'hans zimmer': ['soundtrack', 'orchestral', 'classical'],
  'ludovico einaudi': ['classical', 'minimalism', 'neo-classical'],
  'yiruma': ['classical', 'piano'],
  'john williams': ['soundtrack', 'orchestral'],
  'max richter': ['classical', 'minimalism', 'neo-classical'],
  'chopin': ['classical', 'romantic era'],
  'beethoven': ['classical', 'classical era'],
  'mozart': ['classical', 'classical era'],
  'bach': ['classical', 'baroque era'],
};
